### ISSUE TITLE
Unable to make crowboard work with miryoku

### ISSUE THREAD

**Issue by hansamann** [doesntfazer/CrowBoard#1]
Pls also see here... 
https://github.com/manna-harbour/miryoku/discussions/195

What is the best way to enable miryoku w colemak dh for mac on crowboard?

**Comment by doesntfazer** [comment]
Might be able to get it working in QMK. Here is the PR for that. Not sure when it's going to be brought into the official repo though. 

https://github.com/qmk/qmk_firmware/pull/19141#pullrequestreview-1314546743

**Comment by doesntfazer** [comment]
Closing because it's stale
